spring.application.name=gamestore

## Configurar o banco de Dados
spring.datasource.url = {DB_URL}
spring.datasource.username = {DB_USERNAME}
spring.datasource.password = {DB_PASSWORD}
# obs: nunca colocar senhas em arquivos que vão para o github (isso é feito aqui apenas para fins didáticos)

## Configurações do JPA - hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.generate-ddl = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect